#!/bin/bash
set -euo pipefail

server_version() {
  docker version -f "{{.Server.Version}}"
}

notify_slack() {
  local slack_url=$1
  local msg=$2
  local headers="Content-Type: application/json"
  local color='"color":"#2eb886"'
  local data='{"attachments":[{'"$color"', "text":"'"$msg"'"}]}'
  if [[ $slack_url != "" ]]; then
    curl -H $headers --data $data $slack_url
  fi
}

update_services() {
  local blacklist="$1"
  local supports_detach_option=$2
  local supports_registry_auth=$3
  local detach_option=""
  local registry_auth=""
  local slack_url=$4

  [ $supports_detach_option = true ] && detach_option="--detach=false"
  [ $supports_registry_auth = true ] && registry_auth="--with-registry-auth"

  for service in $(IFS="\n" docker service ls --quiet --filter "${FILTER_SERVICES}"); do
    local name image_with_digest image
    name="$(docker service inspect "$service" -f '{{.Spec.Name}}')"
    if [[ " $blacklist " != *" $name "* ]]; then
      image_with_digest="$(docker service inspect "$service" -f '{{.Spec.TaskTemplate.ContainerSpec.Image}}')"
      image=$(echo "$image_with_digest" | cut -d@ -f1)
      echo "Trying to update service $name with image $image"
      docker service update "$service" $detach_option $registry_auth --image="$image" > /dev/null

      previousImage=$(docker service inspect "$service" -f '{{.PreviousSpec.TaskTemplate.ContainerSpec.Image}}')
      currentImage=$(docker service inspect "$service" -f '{{.Spec.TaskTemplate.ContainerSpec.Image}}')
      if [ "$previousImage" == "$currentImage" ]; then
        echo "No updates to service $name!"
      else
        echo "Service $name was updated!"
        notify_slack $slack_url "Service $name was updated!"
      fi
    fi
  done
}

main() {
  local blacklist sleep_time supports_detach_option supports_registry_auth slack_url
  blacklist="${BLACKLIST_SERVICES:-}"
  sleep_time="${SLEEP_TIME:-5m}"

  supports_detach_option=false
  if [[ "$(server_version)" > "17.05" ]]; then
    supports_detach_option=true
    echo "Enabling synchronous service updates"
  fi

  supports_registry_auth=false
  if [[ ${WITH_REGISTRY_AUTH+x} ]]; then
    supports_registry_auth=true
    echo "Send registry authentication details to swarm agents"
  fi

  slack_url=""
  if [[ ${SLACK_URL} ]]; then
    slack_url=${SLACK_URL}
    echo "Will send notifications to your slack channel"
  fi

  [[ "$blacklist" != "" ]] && echo "Excluding services: $blacklist"

  while true; do
    update_services "$blacklist" "$supports_detach_option" "$supports_registry_auth" "$slack_url"
    echo "Sleeping $sleep_time before next update"
    sleep "$sleep_time"
  done
}

main "$@"
